### ISSUE TITLE
Pop-Up für neues Semester

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/AndroidStundenplanHof#14]
Es könnte noch ein Pop-Up kommen das den Nutzer darauf hinweist das wahrscheinlich gerade ein neues Semester begonnen hat und er doch bitte die Einstellungen anpassen möchte.

Das ein neues Semester begonnen hat könnte man dadurch erfahren das bei getSchedule() keine Vorlesungen vom Server kommen.

**Comment by GlaserDaniel** [comment]
Ok. Wenn vom Server ein leerer Stundenplan kommt bedeutet das nicht gleich das ein neues Semester begonnen hat. Sondern es gibt Semester ohne Stundenplan wie die 7. Semester. Und man kann den Stundenplan des letztes Semesters auch immer noch abholen wenn das neue bereits begonnen hat.

**Comment by avinotec** [comment]
Daher abgelehnt.
