### ISSUE TITLE
Speiseplan bei Sondertarif leer

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/AndroidStundenplanHof#17]
Der Speiseplan ist leer wenn man den Tarif "Sondertarif" wählt.
Der Name für den Sondertarif hat sich geändert.

**Comment by GlaserDaniel** [comment]
Infos von Peter Rill:
"Sondertarif" wurde in scheinbar durch "HföD" ersetzt.
Die Preise über den RSS-Schnittstelle passen aber nicht zur Webseite.

**Comment by PeterRill** [comment]
Ich hatte gerade Kontakt mit dem Studentenwerk, das Problem wird an den dafür Zuständigen weitergeleitet, der mich wieder kontaktieren wird.

**Comment by GlaserDaniel** [comment]
Erstmal gefixt: Sondertarif Hföd Tarif mit der ID 5 wird nun statt Sondertarif mit der ID 4 genommen.
Ob die Preise stimmen noch schauen.

**Comment by cpfeiffer94** [comment]
#resolved
