### ISSUE TITLE
Geht Firebase Push Noti mit Oreo jetzt?

### ISSUE THREAD

**Issue by cpfeiffer94** [HochschuleHofStundenplanapp/AndroidStundenplanHof#18]
Bitte prüft ob bei euch in Oreo die Notification gehen.
Falls nicht beschreibt bitte was schief läuft, damit man sich das näher betrachten kann :-)

**Comment by GlaserDaniel** [comment]
Habe am Emulator mit Android Oreo die Firebase Push Notifications außerhalb der App bekommen. Also die funktionieren.
Die Frage ist jetzt noch ob die die man erhalten kann wenn man in der App ist auch bekommt.

**Comment by jofranz** [comment]
Hab bisher keine Möglichkeit mittels Testserver Notifications zu einer beliebigen Zeit zu senden und kanns daher nicht testen. Hab mit meinem Android 7.1.2 Gerät ein paar von Oreo portierte Features gegen die ich testen kann. Würde ich am Mittwoch in der Vorlesung noch mal ansprechen.

**Comment by avinotec** [comment]
Ist geprüft und funktioniert.
