### ISSUE TITLE
Erinnerungen für Kalendereinträge

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/AndroidStundenplanHof#20]
In der Kalenderschnittstelle und den Einstellungen die folgenden Optionen einbauen:
- [x] Möglichkeit die Zeit (in Minuten) für eine Erinnerung (oder vielleicht auch mehrere) vor einer Vorlesungen einzustellen
- [ ] die Möglichkeit die Uhrzeit für eine Erinnerung bei der ersten Vorlesung am Tag, am Tag davor einzustellen

**Comment by GlaserDaniel** [comment]
In den Einstellungen eine Möglichkeit hinzufügen Erinnerungen für Kalendereinträge einzustellen. (Der Code in der Kalender Synchronisation ist schon vorhanden aber auskommentiert)

Die Einstellungen für den Kalender könnten in den Einstellungen unter einem eigenen Screen zusammengefasst werden. (Dafür ist auch schon auskommentierter Code vorhanden)

**Comment by avinotec** [comment]
eingearbeitet
