### ISSUE TITLE
Push-Notifications kommen nicht an

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/AndroidStundenplanHof#21]
Es scheint das bei manchen die Push-Notifications nicht ankommen.

Die Frage ist woran das liegen könnte. Weil bei den meisten funktionieren sie.

Vermutung:
Eine einfache Erklärung wäre wenn der Nutzer eine Vorlesung zu "Mein Stundenplan" hinzufügt aber für "Stundenplan" Push-Notifications erwartet. Da er ja wenn er eine Vorlesung zu "Mein Stundenplan" hinzufügt nur noch für den "Mein Stundenplan" welche erhält bis dieser wieder leer ist.

Bitte bei Leuten die dieses Problem haben genauer nachfragen wie die Situation bei ihnen ist. Könnte auch einfach nicht in den Einstellungen eingeschalten sein.

Sonst bitte Gerät, Android Version und ausgewählte Vorlesungen hier als Kommentar hinzufügen, um den Fehler vielleicht nachproduzieren zu können. Danke!

**Comment by avinotec** [comment]
So nicht reproduzierbar
