### ISSUE TITLE
Meldungen für den Nutzer beim Synchronisieren des Kalenders

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/AndroidStundenplanHof#23]
Dem Nutzer Meldungen zeigen das der Kalender synchronisiert wird.

**Comment by cpfeiffer94** [comment]
Am Ende des Eintrages der Kalendereinträge den Nutzer darüber informieren, dass die Eintragungen fertig sind (Textlabel unter der Einstellungoption die evtl. den Status anzeigt)

**Comment by GlaserDaniel** [comment]
Also beim hinzufügen und löschen kommt schon ein Toast der sagt das die Synchronisation erfolgreich war. Es könnte sein das es noch Stellen gibt wo so ein Toast fehlt.
Aber was ist genauer mit (Textlabel unter der Einstellungoption die evtl. den Status anzeigt) gemeint?
Etwa in den Einstellungen ein Textlabel das grün ist und "Kalender wird synchronisiert" oder rot und "Kalender wird nicht synchronisiert" oder so ähnlich?

**Comment by avinotec** [comment]
gefixt
