### ISSUE TITLE
Push-Notifications Änderungen

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/AndroidStundenplanHof#26]
- Standardmäßig an
- Text für Änderungen anschalten in den Einstellungen ändern zu so etwas wie "Über Änderungen informieren (Push)"

**Comment by cpfeiffer94** [comment]
Man müsste den Benutzer vorher erklären warum er der App Push Notifications gestatten sollte.

**Comment by jofranz** [comment]
Standardmäßig an finde ich persönlich nicht gut. Der Nutzer muss das schon verstehen und wollen. Man sollte den Nutzer bem ersten App Start nicht überfluten. Ich finde es besser die Rechte erst zu erfragen wenn man sie braucht. So versteht der einfache Nutzer den Zusammenhang besser.
Der Dialog beim Start der App ist ganz okay. Den habe ich nun im "Stundenplan" beim "Alle hinzufügen" noch mal verwendet und die gewünschten Texte geändert.

**Comment by jofranz** [comment]
Dadurch entstandenes Problem...
Reproduzierbar:
- Push Notifications sind in der App de-aktiviert
- Mein Stundenplan ist leer
- Zu den Einstellungen navigieren
- Zum "normalen" Stundenplan navigieren
- Drei Punkte Menü: "Alle hinzufügen"
- Neu eingebaute Frage nach Benachrichtigungen mit JA beantworten
- Zurück zu den Einstellungen navigieren

Hier sind die Push Notificatoins de-aktiviert, da das Einstellungen Fragment nicht neu geladen wird. Die Push Notifications müssten aber dennoch funktionieren - auch wenn ich das nicht testen kann. Beim Neustart der App ist der Haken gesetzt, da das Fragment neu geladen wurde.

Komme gerade auf keine Lösung

**Comment by GlaserDaniel** [comment]
Eine Frage:
Kann es sein das der Teil mit dem einbauen beim "Alle hinzufügen" nicht mit commited ist? :-)
Den in dem Commit https://github.com/HochschuleHofStundenplanapp/AndroidStundenplanHof/commit/cd5e07f30a7c4594cfddd1f6e6d335e8508767b2 ist nur das auf public setzen von showPushNotificationDialog aber nichts beim "Alle hinzufügen".
Und bei mir klappt das nämlich auch gar nicht. :-)
Dann könnte ich auch mal gucken. Wahrscheinlich die preference auch noch auf true setzen, dann müsste es klappen.

**Comment by GlaserDaniel** [comment]
Ach so und das ist keine Abfrage für eine Berechtigung, sondern nur ob es es aktivieren möchte.
Man es könnte es auch einfach so standardmäßig aktivieren. Ist nur ein selbstgebauter Dialog, kein Berechtigungsdialog.
Und wenn er es aktiviert wird er auch über Änderungen im Stundenplan informiert und nicht nur die im "Mein Stundenplan".

**Comment by GlaserDaniel** [comment]
Ok. Ich hab den Dialog an eine andere Stelle verschoben und den Teil mit dem das der Dialog immer wieder kommt entfernt. Wird sonst zu nervig.
Außerdem das Problem mit dem Zurück gehen zu den Einstellungen gefixt.

**Comment by avinotec** [comment]
Standardmäßig schalten wir die Push-Notifications ein.
