### ISSUE TITLE
Einführungsassistenten hinzufügen

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/AndroidStundenplanHof#27]
Eine tolle Möglichkeit dem Nutzer bei der Bedienung zu helfen wäre beim ersten Start einen kleinen Einführungsassistenten (Dialoge mit Erklärung) anzuzeigen.
- Dem Nutzer helfen indem schon mal das Winter oder Sommer Semester ausgewählt ist.
- Zeigen wo man den Studiengang auswählt
- Zeigen wo man das Semester auswählt
- Zeigen wie man zwischen den Fragmenten wechselt, indem man zum "Stundenplan" geht
- Dem Nutzer zeigen das man durch langes drücken eine Vorlesung von "Stundenplan" zu "Mein Stundenplan" hinzufügen kann.
- Den Nutzer fragen ob er nach dem anlegen eines "Mein Stundenplan" die Kalender Synchronisation anschalten möchte
- Vielleicht noch zeigen das man mit gedrückt halten auch wieder Einträge aus "Mein Stundenplan" entfernen kann
- Vielleicht noch Änderungen zeigen
- Vielleicht noch Weiteres

**Comment by avinotec** [comment]
eingearbeitet
